---
title: "R Exercises Session 8"
author: "Sara Birnel Henderson"
output: word_document
---


1.  Create a level 2 header below in Markdown with the name "Answer 1".

## Answer 1

2.  Add an unordered Markdown list of your favorite food dishes and add
    their ingredients as sub-items in the list. You should enter at
    least two dishes with two ingredients each.

-   Food dishes
    -   Chicken Tikka Masala
        -    Chicken breast
        -   Yogurt
        -   Tomato
        -   Tomato Passata
        -   Spices
        -   Onion
        -   Garlic

    -   Flan
        -   Sugar
        -   Eggs
        -   Condensed Milk
        -   Evaporated Milk
        -   Vanilla

3.  Insert an R code chunk below. Show the `summary` of the `Orange`
    dataset. Run a linear regression using the `lm` function to predict
    `circumference` from `age` and assign the result. Show the `summary`
    of the fit object that you assigned.

```{r}
data("Orange")
head(Orange)
summary(Orange)

omodel <- lm(age ~ circumference, data = Orange)
summary(omodel)

```

4.  Add an RMarkdown weblink (in link format) below to your favorite R
    reference website.

[Statistics Globe](https://statisticsglobe.com/)

5.  Replace the author field in the `yaml` header with your name and
    then successfully `knit` the RMarkdown document into a Word
    document.
* done


6.  Follow the [Pull Request instructions on GitHub](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to submit your assignment via GitHub as a Pull Request to the [Assignment8](https://github.com/CUNYSPHCode/Assignment8)
    repository.
* done